### ISSUE TITLE
update to work with 3.0.x

### ISSUE THREAD

**Issue by ergomesh** [slick/slick-codegen-customization-example#1]
Can we get this customized codegen example working in 3.0.x?

I have tried using the documentation here http://slick.typesafe.com/doc/3.0.0/code-generation.html but it points to this example which only works in 2.1.x

**Comment by cvogt** [comment]
did you try to port it? Did you run into problems?

**Comment by ergomesh** [comment]
I actually have a working copy now that I will send you a fork off shortly. Im still working out an issue with large tables in using returning nothing when doing Driver.defaultTables so I will close
